var CartConstants = {
  RECEIVE_SINGLE_PERFORMANCE : "RECEIVE_SINGLE_PERFORMANCE",
  UPDATE_CART_STATUS: "UPDATE_CART_STATUS",
  RESET_CART: "RESET_CART",
  ADD_SINGLE_TICKET: "ADD_SINGLE_TICKET",
  REMOVE_SINGLE_TICKET: "REMOVE_SINGLE_TICKET"
};

module.exports = CartConstants;
