var UserConstants = {
  RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
  RECEIVE_AUTH_ERRORS : "RECEIVE_AUTH_ERRORS",
  DESTROY_CURRENT_USER: "DESTROY_CURRENT_USER"
};

module.exports = UserConstants;
